services:
  postgres:
    image: postgres:17
    container_name: oratoria_postgres

    environment:
      POSTGRES_DB: oratoria_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5434:5432"

    volumes:
      - oratoria_postgres_data:/var/lib/postgresql/data

volumes:
  oratoria_postgres_data:
