package com.oratoria.backend.subscription.entity;

public enum Feature {
    BASIC_VOICE_ANALYSIS,
    ADVANCED_VOICE_ANALYSIS,
    CAMERA_ANALYSIS,
    ADVANCED_STATISTICS,
    FULL_HISTORY,
    SESSION_COMPARISON,
    ADAPTIVE_TRAINING,
    IMPROVISATION,
    COMMUNICATION_STYLES,
    UNLIMITED_SIMULATIONS
}
